# -*- coding: utf-8 -*-
"""API_FLASK.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YC4O-3dCXuhosNIIjJho2eKwIhCcIgoA
"""

#!pip install flask_ngrok

!pip install pyngrok

import pandas as pd
from flask_ngrok import run_with_ngrok
from flask import request, jsonify, Flask
import random as r

app = Flask(__name__)
run_with_ngrok(app)

d = {
    'name': 'Nikola',
    'surname': 'Tesla',
    'idade': 60
}

@app.route('/')

def home():
  '''
  A linha inteira abaixo deve ser escrita em apenas uma linha.
  '''
  return "<marquee><h3> TO CHECK IN PUT ADD '/input' TO THE URL AND TO CHECK OUT PUT ADD '/output' TO THE URL.</h3></marquee>"

@app.route('/input')

def input():
  return jsonify(d)

from flask import Flask, jsonify
import random as r
from pyngrok import ngrok

app = Flask(__name__)

@app.route('/output', methods=['GET', 'POST'])
def predJson():
    pred = r.choice(["positive", "negative"])
    nd = d
    nd['prediction'] = pred
    return jsonify(nd)

if __name__ == '__main__':
    # Iniciar o servidor Flask
    app.run()

    # Iniciar o túnel Ngrok
    ngrok_tunnel = ngrok.connect(5000)  # Substitua a porta 5000 pela porta em que sua aplicação Flask está sendo executada
    public_url = ngrok_tunnel.public_url
    print("Ngrok URL:", public_url)

    # Manter o programa em execução
    input("Pressione Enter para encerrar...")

    # Encerrar o túnel Ngrok e o servidor Flask
    ngrok_tunnel.close()
    ngrok.kill()